@baseUrl = https://localhost:7291

### 
GET {{baseUrl}}/api/In_Memory_Product/without-caching

### 
GET {{baseUrl}}/api/Distributed_Product

####
GET {{baseUrl}}/api/In_Memory_Product/with-caching-old-way

###
GET {{baseUrl}}/api/In_Memory_Product/with-caching-new-way